'use strict';


const fs     = require('fs');
const path   = require('path');
const assert = require('assert');
const crypto = require('crypto');

const pako  = require('../index');

// Load fixtures to test
// return: { 'filename1': content1, 'filename2': content2, ...}
//
function loadSamples(subdir) {
  const result = {};
  const dir = path.join(__dirname, 'fixtures', subdir || 'samples');

  fs.readdirSync(dir).sort().forEach(function (sample) {
    const filepath = path.join(dir, sample);
    const extname  = path.extname(filepath);
    const basename = path.basename(filepath, extname);
    const content  = new Uint8Array(fs.readFileSync(filepath));

    if (basename[0] === '_') { return; } // skip files with name, started with dash

    result[basename] = {
      path: filepath,
      data: content
    };
  });

  return result;
}


// Helper to test deflate/inflate with different options.
// Use zlib streams, because it's the only way to define options.
//
function testSingle(zlib_method, pako_method, sample, options) {
  const zlib_options = Object.assign({}, options);

  // hack for testing negative windowBits
  if (zlib_options.windowBits < 0) { zlib_options.windowBits = -zlib_options.windowBits; }

  const shasum = crypto.createHash('sha1')
    .update(zlib_method).update(JSON.stringify(zlib_options)).update(sample.data).digest('hex');

  const GENERATE_TEXTURES = false;
  const dir = path.join(__dirname, 'fixtures', 'prebuilt');

  if (GENERATE_TEXTURES) {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir);
    }

    // node.js switched to chromium zlib implementation in version v12.17.0,
    // which generates slightly different fixtures.
    // https://github.com/nodejs/node/pull/31201
    //
    // so we use fixtures generated by older node.js versions

    const ver = process.version.match(/^v(\d+)\.(\d+)\.\d+$/);

    if (!(+ver[1] < 12 || +ver[1] === 12 && +ver[2] <= 16)) {
      throw new Error('Please use node.js <=12.16.x to generate these fixtures');
    }

    const fixture = require('zlib')[zlib_method](sample.data, zlib_options);
    fs.writeFileSync(path.join(dir, shasum), fixture);
  }

  const pako_result = pako_method(sample.data, options);
  const zlib_result = fs.readFileSync(path.join(dir, shasum));

  // One more hack: gzip header contains OS code, that can vary.
  // Override OS code if requested. For simplicity, we assume it on fixed
  // position (= no additional gzip headers used)
  if (options.ignore_os) zlib_result[9] = pako_result[9];

  assert.deepStrictEqual(pako_result, new Uint8Array(zlib_result));
}


function testSamples(zlib_method, pako_method, samples, options) {

  Object.keys(samples).forEach(function (name) {
    const sample = samples[name];

    testSingle(zlib_method, pako_method, sample, options);
  });
}


function testInflate(samples, inflateOptions, deflateOptions) {
  let name, data, deflated, inflated;

  // inflate options have windowBits = 0 to force autodetect window size
  //
  for (name in samples) {
    if (!samples.hasOwnProperty(name)) continue;
    data = samples[name].data;

    deflated = pako.deflate(data, deflateOptions);
    inflated = pako.inflate(deflated, inflateOptions);

    assert.deepStrictEqual(inflated, data);
  }
}


module.exports.testSamples = testSamples;
module.exports.testInflate = testInflate;
module.exports.loadSamples = loadSamples;
