import {
  messages,
  ZStream,
  zlibInflateInit2,
  zlibInflateSetDictionary,
  zlibInflate,
  zlibInflateReset,
  zlibInflateEnd
} from './zlib.mjs';
import type { Z_CallStatus, Z_FlushMode } from './zlib.mjs';
import { flattenChunks } from './utils.ts';

const toString = Object.prototype.toString;

/* Public constants ==========================================================*/
/* ===========================================================================*/

import {
  Z_NO_FLUSH, Z_FINISH,
  Z_OK, Z_STREAM_END, Z_NEED_DICT, Z_STREAM_ERROR, Z_DATA_ERROR, Z_MEM_ERROR, Z_BUF_ERROR
} from './zlib/constants.mjs';

/* ===========================================================================*/

/** @inline */
type InflateInput = Uint8Array | ArrayBuffer;

interface InflateOptions {
  /**
   * Window size. See the
   * [zlib manual](http://zlib.net/manual.html#Advanced) for more information.
   * @group zlib options
   */
  windowBits?: number;
  /**
   * Initial dictionary. See the
   * [zlib manual](http://zlib.net/manual.html#Advanced) for more information.
   * @group zlib options
   */
  dictionary?: Uint8Array | ArrayBuffer;
  /**
   * Size of generated data chunks (64K by default).
   * @group Extensions
   */
  chunkSize?: number;
  /**
   * Do raw inflate. Say that we work with raw stream, if you don't wish to
   * specify negative `windowBits` implicitly.
   * @group Extensions
   */
  raw?: boolean;
}

const defaultOptions: Required<InflateOptions> = {
  chunkSize: 1024 * 64,
  windowBits: 15,
  raw: false,
  dictionary: new Uint8Array(0)
};

/**
 * Generic JS-style wrapper for zlib calls. If you don't need
 * streaming behaviour - use more simple functions: {@link inflate}
 * and {@link inflateRaw}.
 */
class Inflate {
  private options: Required<InflateOptions>;

  /**
   * Error code after inflate finished. 0 (Z_OK) on success.
   * Should be checked if broken data possible.
   */
  err: Z_CallStatus;

  /** Error message, if {@link Inflate.err} != 0. */
  msg: string;

  private ended: boolean;
  private started: boolean;

  /**
   * Chunks of output data, if {@link Inflate.onData} not overridden.
   * @internal
   */
  chunks: Uint8Array[];

  private strm: ZStream;

  /**
   * Uncompressed result, generated by default {@link Inflate.onData}
   * and {@link Inflate.onEnd} handlers. Filled after you push last chunk
   * (call {@link Inflate.push} with `Z_FINISH` / `true` param).
   */
  result?: Uint8Array;

  /**
   * Creates new inflator instance with specified params. Throws exception
   * on bad params. See {@link InflateOptions} for the list of supported options.
   *
   * By default, when no options set, autodetect deflate/gzip data format via
   * wrapper header.
   *
   * @example
   * ```javascript
   * const pako = require('pako')
   * const chunk1 = new Uint8Array([1,2,3,4,5,6,7,8,9])
   * const chunk2 = new Uint8Array([10,11,12,13,14,15,16,17,18,19]);
   *
   * const inflate = new pako.Inflate({ level: 3});
   *
   * inflate.push(chunk1, false);
   * inflate.push(chunk2, true);  // true -> last chunk
   *
   * if (inflate.err) { throw new Error(inflate.err); }
   *
   * console.log(inflate.result);
   * ```
   */
  constructor(options: InflateOptions = {}) {
    this.options = Object.assign({}, defaultOptions, options);

    const opt = this.options;

    // Force window size for `raw` data, if not set directly,
    // because we have no header for autodetect.
    if (opt.raw && (opt.windowBits >= 0) && (opt.windowBits < 16)) {
      opt.windowBits = -opt.windowBits;
      if (opt.windowBits === 0) { opt.windowBits = -15; }
    }

    // If `windowBits` not defined (and mode not raw) - set autodetect flag for gzip/deflate
    if ((opt.windowBits >= 0) && (opt.windowBits < 16) &&
        !options.windowBits) {
      opt.windowBits += 32;
    }

    // Gzip header has no info about windows size, we can do autodetect only
    // for deflate. So, if window size not set, force it to max when gzip possible
    if ((opt.windowBits > 15) && (opt.windowBits < 48)) {
      // bit 3 (16) -> gzipped data
      // bit 4 (32) -> autodetect gzip/deflate
      if ((opt.windowBits & 15) === 0) {
        opt.windowBits |= 15;
      }
    }

    this.err    = 0;      // error code, if happens (0 = Z_OK)
    this.msg    = '';     // error message
    this.ended  = false;  // used to avoid multiple onEnd() calls
    this.started = false; // used to call onStart() only once
    this.chunks = [];     // chunks of compressed data

    this.strm   = new ZStream();
    this.strm.avail_out = 0;

    let status  = zlibInflateInit2(
      this.strm,
      opt.windowBits
    );

    if (status !== Z_OK) {
      throw new Error(messages[status]);
    }

    if (toString.call(opt.dictionary) === '[object ArrayBuffer]') {
      opt.dictionary = new Uint8Array(opt.dictionary as ArrayBuffer);
    }

    const dictionary = opt.dictionary as Uint8Array;

    if (opt.raw && dictionary.length) {
      status = zlibInflateSetDictionary(this.strm, dictionary);
      if (status !== Z_OK) {
        throw new Error(messages[status]);
      }
    }
  }

  /**
   * Sends input data to inflate pipe, generating {@link Inflate.onData} calls with
   * new output chunks. Returns `true` on success. If end of stream detected,
   * {@link Inflate.onEnd} will be called.
   *
   * `flush_mode` is not needed for normal operation, because end of stream
   * detected automatically. You may try to use it for advanced things, but
   * this functionality was not tested.
   *
   * On fail call {@link Inflate.onEnd} with error code and return false.
   *
   * @param flush_mode 0..6 for corresponding {@link Z_NO_FLUSH}..{@link Z_TREES}
   *   flush modes. See constants. Skipped or `false` means {@link Z_NO_FLUSH},
   *   `true` means {@link Z_FINISH}.
   *
   * @example
   * ```javascript
   * push(chunk, false); // push one of data chunks
   * ...
   * push(chunk, true);  // push last chunk
   * ```
   */
  push(data: InflateInput, flush_mode: Z_FlushMode | boolean = false): boolean {
    const strm = this.strm;
    const chunkSize = this.options.chunkSize;
    let status: Z_CallStatus;
    let _flush_mode: Z_FlushMode;
    let last_avail_out: number;

    if (this.ended) return false;

    if (typeof flush_mode === 'number') _flush_mode = flush_mode;
    else _flush_mode = flush_mode === true ? Z_FINISH : Z_NO_FLUSH;

    // Convert data if needed
    if (toString.call(data) === '[object ArrayBuffer]') {
      strm.input = new Uint8Array(data as ArrayBuffer);
    } else {
      strm.input = data as Uint8Array;
    }

    strm.next_in = 0;
    strm.avail_in = strm.input.length;

    if (!this.started) {
      this.started = true;
      this.onStart(strm);
    }

    for (;;) {
      if (strm.avail_out === 0) {
        strm.output = new Uint8Array(chunkSize);
        strm.next_out = 0;
        strm.avail_out = chunkSize;
      }

      status = zlibInflate(strm, _flush_mode);

      if (status === Z_NEED_DICT) {
        const dictionary = this.options.dictionary as Uint8Array;

        if (dictionary.length) {
          status = zlibInflateSetDictionary(strm, dictionary);

          if (status === Z_OK) {
            status = zlibInflate(strm, _flush_mode);
          } else if (status === Z_DATA_ERROR) {
            // Replace code with more verbose
            status = Z_NEED_DICT;
          }
        }
      }

      // Only the gzip format defines concatenated members (RFC 1952: a gzip file
      // is "a series of members"). A zlib stream (RFC 1950) ends after its
      // ADLER32, and a raw DEFLATE stream (RFC 1951) ends after its final block -
      // neither format allows anything to follow, so bytes after the end are not
      // ours to interpret and must be left in the input. Restart decoding only
      // for a gzip member: `state.flags` is non-zero only once a gzip header has
      // actually been decoded (it stays 0 for a zlib member, even when the format
      // was auto-detected and the gzip bit of `wrap` is set). A trailing zero
      // byte is padding, not the start of a member (no member can begin with 0).
      while (strm.avail_in > 0 &&
             status === Z_STREAM_END &&
             (strm.state.wrap & 2) && (strm.state as any).flags !== 0 &&
             strm.input[strm.next_in] !== 0)
      {
        zlibInflateReset(strm);
        status = zlibInflate(strm, _flush_mode);
      }

      switch (status) {
        case Z_STREAM_ERROR:
        case Z_DATA_ERROR:
        case Z_NEED_DICT:
        case Z_MEM_ERROR:
          this.onEnd(status);
          this.ended = true;
          return false;
      }

      // Remember real `avail_out` value before output buffer counters are reset.
      last_avail_out = strm.avail_out;

      if (strm.next_out) {
        // Flush output if buffer is full, stream ended, or an explicit flush was
        // requested (e.g. Z_SYNC_FLUSH) - to push out the tail, same as node's zlib.
        if (strm.avail_out === 0 || status === Z_STREAM_END || _flush_mode > 0) {

          this.onData(strm.output.length === strm.next_out ? strm.output : strm.output.subarray(0, strm.next_out));

          // Force a fresh output buffer on next iteration / next push, so the
          // already emitted tail is not sent again.
          strm.avail_out = 0;
          strm.next_out = 0;
        }
      }

      // A full output buffer means there may be more to produce - allocate a new
      // one and call inflate again. The status depends on the flush mode: with
      // Z_NO_FLUSH a full buffer is reported as Z_OK, but with Z_FINISH the same
      // situation is reported as Z_BUF_ERROR ("could not make progress now",
      // non-fatal) even though output is still pending. Both must continue; the
      // distinction that matters is purely "was the output buffer exhausted".
      if ((status === Z_OK || status === Z_BUF_ERROR) && last_avail_out === 0) continue;

      // Finalize if end of stream reached.
      if (status === Z_STREAM_END) {
        status = zlibInflateEnd(this.strm);
        this.onEnd(status);
        this.ended = true;
        return true;
      }

      if (strm.avail_in === 0) {
        // Input is exhausted. If the caller declared this the end of the stream
        // (Z_FINISH) but we never saw Z_STREAM_END, the compressed data ended
        // before its terminating marker - i.e. it is truncated/incomplete. That
        // is an error: returning the partial output as success would be
        // indistinguishable from a complete decode, hiding the data loss. Report
        // it via Z_BUF_ERROR. (Reached only when the output buffer still had room
        // - a full buffer is handled by the `continue` above - so this genuinely
        // means "ran out of input", not "ran out of output".)
        if (_flush_mode === Z_FINISH) {
          status = zlibInflateEnd(this.strm);
          this.onEnd(status === Z_OK ? Z_BUF_ERROR : status);
          this.ended = true;
          return false;
        }
        break;
      }
    }

    return true;
  }


  /**
   * Called once before the first low-level inflate call.
   *
   * Override this handler to attach low-level inflate state, for example to read
   * gzip header metadata:
   *
   * ```javascript
   * import { Inflate, GZheader, zlibInflateGetHeader } from 'pako';
   *
   * const inflator = new Inflate();
   *
   * inflator.onStart = function (strm) {
   *   this.header = new GZheader();
   *   zlibInflateGetHeader(strm, this.header);
   * };
   *
   * inflator.push(data, true);
   * console.log(inflator.header.name);
   * ```
   */
  onStart(strm: ZStream): void {}


  /**
   * By default, stores data blocks in {@link Inflate.chunks} property and glue
   * those in {@link Inflate.onEnd}. Override this handler, if you need another behaviour.
   *
   * @param chunk output data.
   */
  onData(chunk: Uint8Array): void {
    this.chunks.push(chunk);
  }


  /**
   * Called either after you tell inflate that the input stream is
   * complete ({@link Z_FINISH}). By default - join collected {@link Inflate.chunks},
   * free memory and fill {@link Inflate.result} / {@link Inflate.err} properties.
   *
   * @param status inflate status. 0 ({@link Z_OK}) on success, other if not.
   */
  onEnd(status: Z_CallStatus): void {
    // On success - join
    if (status === Z_OK) {
      this.result = flattenChunks(this.chunks);
    }
    this.chunks = [];
    this.err = status;
    this.msg = this.strm.msg;
  }
}


/**
 * Decompress `data` with inflate/ungzip and `options`. Autodetect `gzip`/`zlib`
 * format via wrapper header — so {@link ungzip} is just a convenience alias of
 * this function. See {@link InflateOptions} for zlib options. Set
 * `toText: true` to decode the result as UTF-8 text.
 *
 * @example
 * ```javascript
 * const pako = require('pako');
 * const input = pako.deflate(new Uint8Array([1,2,3,4,5,6,7,8,9]));
 * let output;
 *
 * try {
 *   output = pako.inflate(input);
 * } catch (err) {
 *   console.log(err);
 * }
 * ```
 */
function inflate<O extends InflateOptions & { toText?: boolean }>(
  input: InflateInput,
  options: O = {} as O
): O extends { toText: true } ? string : Uint8Array {
  const inflator = new Inflate(options);

  inflator.push(input, true);

  // That will never happens, if you don't cheat with options :)
  if (inflator.err) throw inflator.msg || messages[inflator.err];

  const result = inflator.result as Uint8Array;

  return (options.toText ? new TextDecoder().decode(result) : result) as
    O extends { toText: true } ? string : Uint8Array;
}


/**
 * The same as {@link inflate}, but consumes raw data, without wrapper
 * (header and adler32 crc).
 */
function inflateRaw<O extends InflateOptions & { toText?: boolean }>(
  input: InflateInput,
  options: O = {} as O
): O extends { toText: true } ? string : Uint8Array {
  return inflate<O>(input, { ...options, raw: true } as O);
}


/**
 * The same as {@link inflate}. Provided under a named export for convenience:
 * {@link inflate} already autodetects the gzip format from the wrapper header,
 * so there is no separate decoding logic here.
 */
function ungzip<O extends InflateOptions & { toText?: boolean }>(
  input: InflateInput,
  options: O = {} as O
): O extends { toText: true } ? string : Uint8Array {
  return inflate<O>(input, options);
}


export { Inflate, inflate, inflateRaw, ungzip };
export type { InflateInput, InflateOptions };
