import {
  messages,
  ZStream,
  zlibInflateInit2,
  zlibInflateSetDictionary,
  zlibInflate,
  zlibInflateReset,
  zlibInflateEnd
} from './zlib.mjs';
import type { Z_CallStatus, Z_FlushMode } from './zlib.mjs';
import { flattenChunks } from './utils.ts';

const toString = Object.prototype.toString;

/* Public constants ==========================================================*/
/* ===========================================================================*/

import {
  Z_NO_FLUSH, Z_FINISH,
  Z_OK, Z_STREAM_END, Z_NEED_DICT, Z_STREAM_ERROR, Z_DATA_ERROR, Z_MEM_ERROR, Z_BUF_ERROR
} from './zlib/constants.mjs';

/* ===========================================================================*/

/** @inline */
type InflateInput = Uint8Array | ArrayBuffer;
/** @inline */
type InflateChunk = Uint8Array | string;

interface InflateOptions {
  chunkSize?: number;
  windowBits?: number;
  raw?: boolean;
  to?: string;
  dictionary?: Uint8Array | ArrayBuffer;
}

const defaultOptions: Required<InflateOptions> = {
  chunkSize: 1024 * 64,
  windowBits: 15,
  raw: false,
  to: '',
  dictionary: new Uint8Array(0)
};

/**
 * class Inflate
 *
 * Generic JS-style wrapper for zlib calls. If you don't need
 * streaming behaviour - use more simple functions: [[inflate]]
 * and [[inflateRaw]].
 **/

/* internal
 * inflate.chunks -> Array
 *
 * Chunks of output data, if [[Inflate#onData]] not overridden.
 **/

/**
 * Inflate.result -> Uint8Array|String
 *
 * Uncompressed result, generated by default [[Inflate#onData]]
 * and [[Inflate#onEnd]] handlers. Filled after you push last chunk
 * (call [[Inflate#push]] with `Z_FINISH` / `true` param).
 **/

/**
 * Inflate.err -> Number
 *
 * Error code after inflate finished. 0 (Z_OK) on success.
 * Should be checked if broken data possible.
 **/

/**
 * Inflate.msg -> String
 *
 * Error message, if [[Inflate.err]] != 0
 **/


/**
 * new Inflate(options)
 * - options (Object): zlib inflate options.
 *
 * Creates new inflator instance with specified params. Throws exception
 * on bad params. Supported options:
 *
 * - `windowBits`
 * - `dictionary`
 * [http://zlib.net/manual.html#Advanced](http://zlib.net/manual.html#Advanced)
 * for more information on these.
 *
 * Additional options, for internal needs:
 *
 * - `chunkSize` - size of generated data chunks (16K by default)
 * - `raw` (Boolean) - do raw inflate
 * - `to` (String) - if equal to 'string', then result will be converted
 *   from utf8 to utf16 (javascript) string. When string output requested,
 *   chunk length can differ from `chunkSize`, depending on content.
 *
 * By default, when no options set, autodetect deflate/gzip data format via
 * wrapper header.
 *
 * ##### Example:
 *
 * ```javascript
 * const pako = require('pako')
 * const chunk1 = new Uint8Array([1,2,3,4,5,6,7,8,9])
 * const chunk2 = new Uint8Array([10,11,12,13,14,15,16,17,18,19]);
 *
 * const inflate = new pako.Inflate({ level: 3});
 *
 * inflate.push(chunk1, false);
 * inflate.push(chunk2, true);  // true -> last chunk
 *
 * if (inflate.err) { throw new Error(inflate.err); }
 *
 * console.log(inflate.result);
 * ```
 **/
class Inflate {
  private options: Required<InflateOptions>;
  err: Z_CallStatus;
  msg: string;
  private ended: boolean;
  private started: boolean;
  chunks: InflateChunk[];
  private textDecoder: TextDecoder | null;
  private strm: ZStream;
  result?: Uint8Array | string;

  constructor(options?: InflateOptions) {
    this.options = Object.assign({}, defaultOptions, options || {});

    const opt = this.options;

    // Force window size for `raw` data, if not set directly,
    // because we have no header for autodetect.
    if (opt.raw && (opt.windowBits >= 0) && (opt.windowBits < 16)) {
      opt.windowBits = -opt.windowBits;
      if (opt.windowBits === 0) { opt.windowBits = -15; }
    }

    // If `windowBits` not defined (and mode not raw) - set autodetect flag for gzip/deflate
    if ((opt.windowBits >= 0) && (opt.windowBits < 16) &&
        !(options && options.windowBits)) {
      opt.windowBits += 32;
    }

    // Gzip header has no info about windows size, we can do autodetect only
    // for deflate. So, if window size not set, force it to max when gzip possible
    if ((opt.windowBits > 15) && (opt.windowBits < 48)) {
      // bit 3 (16) -> gzipped data
      // bit 4 (32) -> autodetect gzip/deflate
      if ((opt.windowBits & 15) === 0) {
        opt.windowBits |= 15;
      }
    }

    this.err    = 0;      // error code, if happens (0 = Z_OK)
    this.msg    = '';     // error message
    this.ended  = false;  // used to avoid multiple onEnd() calls
    this.started = false; // used to call onStart() only once
    this.chunks = [];     // chunks of compressed data
    this.textDecoder = opt.to === 'string' ? new TextDecoder() : null;

    this.strm   = new ZStream();
    this.strm.avail_out = 0;

    let status  = zlibInflateInit2(
      this.strm,
      opt.windowBits
    );

    if (status !== Z_OK) {
      throw new Error(messages[status]);
    }

    if (toString.call(opt.dictionary) === '[object ArrayBuffer]') {
      opt.dictionary = new Uint8Array(opt.dictionary as ArrayBuffer);
    }

    const dictionary = opt.dictionary as Uint8Array;

    if (opt.raw && dictionary.length) {
      status = zlibInflateSetDictionary(this.strm, dictionary);
      if (status !== Z_OK) {
        throw new Error(messages[status]);
      }
    }
  }

/**
 * Inflate#push(data[, flush_mode]) -> Boolean
 * - data (Uint8Array|ArrayBuffer): input data
 * - flush_mode (Number|Boolean): 0..6 for corresponding Z_NO_FLUSH..Z_TREE
 *   flush modes. See constants. Skipped or `false` means Z_NO_FLUSH,
 *   `true` means Z_FINISH.
 *
 * Sends input data to inflate pipe, generating [[Inflate#onData]] calls with
 * new output chunks. Returns `true` on success. If end of stream detected,
 * [[Inflate#onEnd]] will be called.
 *
 * `flush_mode` is not needed for normal operation, because end of stream
 * detected automatically. You may try to use it for advanced things, but
 * this functionality was not tested.
 *
 * On fail call [[Inflate#onEnd]] with error code and return false.
 *
 * ##### Example
 *
 * ```javascript
 * push(chunk, false); // push one of data chunks
 * ...
 * push(chunk, true);  // push last chunk
 * ```
 **/
  push(data: InflateInput, flush_mode: Z_FlushMode | boolean = false): boolean {
    const strm = this.strm;
    const chunkSize = this.options.chunkSize;
    let status: Z_CallStatus;
    let _flush_mode: Z_FlushMode;
    let last_avail_out: number;

    if (this.ended) return false;

    if (typeof flush_mode === 'number') _flush_mode = flush_mode;
    else _flush_mode = flush_mode === true ? Z_FINISH : Z_NO_FLUSH;

    // Convert data if needed
    if (toString.call(data) === '[object ArrayBuffer]') {
      strm.input = new Uint8Array(data as ArrayBuffer);
    } else {
      strm.input = data as Uint8Array;
    }

    strm.next_in = 0;
    strm.avail_in = strm.input.length;

    if (!this.started) {
      this.started = true;
      this.onStart(strm);
    }

    for (;;) {
      if (strm.avail_out === 0) {
        strm.output = new Uint8Array(chunkSize);
        strm.next_out = 0;
        strm.avail_out = chunkSize;
      }

      status = zlibInflate(strm, _flush_mode);

      if (status === Z_NEED_DICT) {
        const dictionary = this.options.dictionary as Uint8Array;

        if (dictionary.length) {
          status = zlibInflateSetDictionary(strm, dictionary);

          if (status === Z_OK) {
            status = zlibInflate(strm, _flush_mode);
          } else if (status === Z_DATA_ERROR) {
            // Replace code with more verbose
            status = Z_NEED_DICT;
          }
        }
      }

      // Only the gzip format defines concatenated members (RFC 1952: a gzip file
      // is "a series of members"). A zlib stream (RFC 1950) ends after its
      // ADLER32, and a raw DEFLATE stream (RFC 1951) ends after its final block -
      // neither format allows anything to follow, so bytes after the end are not
      // ours to interpret and must be left in the input. Restart decoding only
      // for a gzip member: `state.flags` is non-zero only once a gzip header has
      // actually been decoded (it stays 0 for a zlib member, even when the format
      // was auto-detected and the gzip bit of `wrap` is set). A trailing zero
      // byte is padding, not the start of a member (no member can begin with 0).
      while (strm.avail_in > 0 &&
             status === Z_STREAM_END &&
             (strm.state.wrap & 2) && (strm.state as any).flags !== 0 &&
             strm.input[strm.next_in] !== 0)
      {
        zlibInflateReset(strm);
        status = zlibInflate(strm, _flush_mode);
      }

      switch (status) {
        case Z_STREAM_ERROR:
        case Z_DATA_ERROR:
        case Z_NEED_DICT:
        case Z_MEM_ERROR:
          this.onEnd(status);
          this.ended = true;
          return false;
      }

      // Remember real `avail_out` value before output buffer counters are reset.
      last_avail_out = strm.avail_out;

      if (strm.next_out) {
        // Flush output if buffer is full, stream ended, or an explicit flush was
        // requested (e.g. Z_SYNC_FLUSH) - to push out the tail, same as node's zlib.
        if (strm.avail_out === 0 || status === Z_STREAM_END || _flush_mode > 0) {

          if (this.options.to === 'string') {

            let str = this.textDecoder!.decode(strm.output.subarray(0, strm.next_out), { stream: true });

            strm.next_out = 0;
            strm.avail_out = chunkSize;

            if (str) this.onData(str);

          } else {
            this.onData(strm.output.length === strm.next_out ? strm.output : strm.output.subarray(0, strm.next_out));

            // Force a fresh output buffer on next iteration / next push, so the
            // already emitted tail is not sent again.
            strm.avail_out = 0;
            strm.next_out = 0;
          }
        }
      }

      // A full output buffer means there may be more to produce - allocate a new
      // one and call inflate again. The status depends on the flush mode: with
      // Z_NO_FLUSH a full buffer is reported as Z_OK, but with Z_FINISH the same
      // situation is reported as Z_BUF_ERROR ("could not make progress now",
      // non-fatal) even though output is still pending. Both must continue; the
      // distinction that matters is purely "was the output buffer exhausted".
      if ((status === Z_OK || status === Z_BUF_ERROR) && last_avail_out === 0) continue;

      // Finalize if end of stream reached.
      if (status === Z_STREAM_END) {
        status = zlibInflateEnd(this.strm);
        if (status === Z_OK && this.options.to === 'string') {
          const str = this.textDecoder!.decode();
          if (str) this.onData(str);
        }
        this.onEnd(status);
        this.ended = true;
        return true;
      }

      if (strm.avail_in === 0) {
        // Input is exhausted. If the caller declared this the end of the stream
        // (Z_FINISH) but we never saw Z_STREAM_END, the compressed data ended
        // before its terminating marker - i.e. it is truncated/incomplete. That
        // is an error: returning the partial output as success would be
        // indistinguishable from a complete decode, hiding the data loss. Report
        // it via Z_BUF_ERROR. (Reached only when the output buffer still had room
        // - a full buffer is handled by the `continue` above - so this genuinely
        // means "ran out of input", not "ran out of output".)
        if (_flush_mode === Z_FINISH) {
          status = zlibInflateEnd(this.strm);
          this.onEnd(status === Z_OK ? Z_BUF_ERROR : status);
          this.ended = true;
          return false;
        }
        break;
      }
    }

    return true;
  }


/**
 * Inflate#onStart(strm) -> Void
 * - strm (ZStream): low-level zlib stream.
 *
 * Called once before the first low-level inflate call.
 *
 * Override this handler to attach low-level inflate state, for example to read
 * gzip header metadata:
 *
 * ```javascript
 * import { Inflate, GZheader, zlibInflateGetHeader } from 'pako';
 *
 * const inflator = new Inflate();
 *
 * inflator.onStart = function (strm) {
 *   this.header = new GZheader();
 *   zlibInflateGetHeader(strm, this.header);
 * };
 *
 * inflator.push(data, true);
 * console.log(inflator.header.name);
 * ```
 **/
  onStart(strm: ZStream): void {}


/**
 * Inflate#onData(chunk) -> Void
 * - chunk (Uint8Array|String): output data. When string output requested,
 *   each chunk will be string.
 *
 * By default, stores data blocks in `chunks[]` property and glue
 * those in `onEnd`. Override this handler, if you need another behaviour.
 **/
  onData(chunk: InflateChunk): void {
    this.chunks.push(chunk);
  }


/**
 * Inflate#onEnd(status) -> Void
 * - status (Number): inflate status. 0 (Z_OK) on success,
 *   other if not.
 *
 * Called either after you tell inflate that the input stream is
 * complete (Z_FINISH). By default - join collected chunks,
 * free memory and fill `results` / `err` properties.
 **/
  onEnd(status: Z_CallStatus): void {
    // On success - join
    if (status === Z_OK) {
      if (this.options.to === 'string') {
        this.result = this.chunks.join('');
      } else {
        this.result = flattenChunks(this.chunks as Uint8Array[]);
      }
    }
    this.chunks = [];
    this.err = status;
    this.msg = this.strm.msg;
  }
}


/**
 * inflate(data[, options]) -> Uint8Array|String
 * - data (Uint8Array|ArrayBuffer): input data to decompress.
 * - options (Object): zlib inflate options.
 *
 * Decompress `data` with inflate/ungzip and `options`. Autodetect
 * format via wrapper header by default. That's why we don't provide
 * separate `ungzip` method.
 *
 * Supported options are:
 *
 * - windowBits
 * - dictionary
 *
 * [http://zlib.net/manual.html#Advanced](http://zlib.net/manual.html#Advanced)
 * for more information.
 *
 * Sugar (options):
 *
 * - `raw` (Boolean) - say that we work with raw stream, if you don't wish to specify
 *   negative windowBits implicitly.
 * - `to` (String) - if equal to 'string', then result will be converted
 *   from utf8 to utf16 (javascript) string. When string output requested,
 *   chunk length can differ from `chunkSize`, depending on content.
 *
 *
 * ##### Example:
 *
 * ```javascript
 * const pako = require('pako');
 * const input = pako.deflate(new Uint8Array([1,2,3,4,5,6,7,8,9]));
 * let output;
 *
 * try {
 *   output = pako.inflate(input);
 * } catch (err) {
 *   console.log(err);
 * }
 * ```
 **/
function inflate(input: InflateInput, options: InflateOptions & { to: 'string' }): string;
function inflate(input: InflateInput, options?: InflateOptions): Uint8Array;
function inflate(input: InflateInput, options: InflateOptions = {}): Uint8Array | string {
  const inflator = new Inflate(options);

  inflator.push(input, true);

  // That will never happens, if you don't cheat with options :)
  if (inflator.err) throw inflator.msg || messages[inflator.err];

  return inflator.result as Uint8Array | string;
}


/**
 * inflateRaw(data[, options]) -> Uint8Array|String
 * - data (Uint8Array|ArrayBuffer): input data to decompress.
 * - options (Object): zlib inflate options.
 *
 * The same as [[inflate]], but creates raw data, without wrapper
 * (header and adler32 crc).
 **/
function inflateRaw(input: InflateInput, options: InflateOptions & { to: 'string' }): string;
function inflateRaw(input: InflateInput, options?: InflateOptions): Uint8Array;
function inflateRaw(input: InflateInput, options: InflateOptions = {}): Uint8Array | string {
  return inflate(input, Object.assign({}, options, { raw: true }));
}


/**
 * ungzip(data[, options]) -> Uint8Array|String
 * - data (Uint8Array|ArrayBuffer): input data to decompress.
 * - options (Object): zlib inflate options.
 *
 * Just shortcut to [[inflate]], because it autodetects format
 * by header.content. Done for convenience.
 **/


export { Inflate, inflate, inflateRaw, inflate as ungzip };
export type { InflateInput, InflateOptions };
